export const PortfolioData = [
  {
    id: 1,
    title: "BlockVideo - Video Streaming DAPP",
    subtitle: "A decentralized video streaming platform.",
    image: "/assets/dapp.png",
    link: "https://github.com/aitsamahad/blockVideo",
    tech: [
      "ReactJS",
      "Ethereum",
      "Solidity",
      "Truffle",
      "Ganache",
      "IPFS",
      "Web3",
      "Bootstrap",
    ],
    madeAt: "--",
  },
  {
    id: 2,
    title: "iClerk - Invoicing Solution",
    subtitle: "Move towards a better invoicing solution.",
    image: "/assets/iclerk.jpeg",
    link: "https://paygate-frontend-dev.herokuapp.com",
    tech: [
      "ReactJS",
      "Redux",
      "Redux Toolkit",
      "Knox",
      "Rest API",
      "Material-UI",
      "NextJS",
      "Context API",
      "Websockets",
      "Styled Components",
      "Heroku",
      "Stripe",
    ],
    madeAt: "XIOTS",
  },
  {
    id: 3,
    title: "Drop - Multi Vendor eCommerce",
    subtitle: "Your favourite restaurants, delivered.",
    image: "/assets/drop.jpeg",
    link: "https://droponline.co.uk",
    tech: [
      "ReactJS",
      "Session Authentication",
      "Reverse Proxy",
      "Rest API",
      "Material-UI",
      "NextJS",
      "Context API",
      "Javascript CSS",
      "Heroku",
      "Stripe",
    ],
    madeAt: "XIOTS",
  },
  {
    id: 4,
    title: "Medicus - iOS/Android (Rest APIs)",
    subtitle: "Best doctors around the world, at your service.",
    image: "/assets/medicus.png",
    link: "#",
    tech: [
      "ExpressJS",
      "NodeJS",
      "Rest API",
      "GraphQL API(s)",
      "Apollo",
      "Firebase",
      "FCM Notifications",
      "Postgres",
      "Sequelize",
      "NGINX/VPS Deployement",
    ],
    madeAt: "iDevelopStudio",
  },
  //   {
  //     title: "Drop Vendor - Vendor Dashboard",
  //     subtitle: "Manage your catalogue at your ease.",
  //   },
  {
    id: 5,
    title: "ROY - iOS/Android (Rest APIs)",
    subtitle: "Get your answers anonymously and easily.",
    image: "/assets/roy.png",
    link: "#",
    tech: [
      "ExpressJS",
      "NodeJS",
      "Rest API",
      "Firebase",
      "FCM Notifications",
      "MySQL",
      "Sequelize",
    ],
    madeAt: "iDevelopStudio",
  },
  //   {
  //     title: "Drop EPOS - Restaurant Dashboard",
  //     subtitle: "Manage your store and stocks availibility.",
  //   },
  {
    id: 6,
    title: "WhatsOn - iOS/Android (Rest APIs)",
    subtitle: "Events ticket booking application.",
    image: "/assets/whatson.png",
    link: "#",
    tech: [
      "ExpressJS",
      "NodeJS",
      "Rest API",
      "Firebase",
      "FCM Notifications",
      "MongoDB",
      "Mongoose",
      "NGINX/VPS Deployement",
    ],
    madeAt: "iDevelopStudio",
  },
]
